version: "3.9"

services:
  db:
    image: postgres:15.5-alpine
    container_name: sck-database
    environment:
      - POSTGRES_PASSWORD=123456
      - TZ=Asia/Bangkok
    ports:
      - 5432:5432
    volumes:
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - sck

  backend:
    image: cosmtrek/air
    container_name: sck-backend
    working_dir: /app
    ports:
      - 8000:8000
      - 2345:2345 # Add this line for debugging
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_URL=postgres://postgres:123456@sck-database:5432/postgres
    volumes:
      - ./:/app/
    networks:
      - sck

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - sck

networks:
  sck: {}
