version: "3.9"

services:
  db:
    container_name: sck-database
    image: postgres:15.5-alpine
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - sck

  backend:
    container_name: sck-backend
    build: .
    working_dir: /app
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_ENV=development
      - APP_PORT=3000
      - DB_URL=postgres://postgres:123456@sck-database:5432/postgres
    networks:
      - sck

networks:
  sck: {}
