version: "3.9"

services:
  db:
    image: postgres:15.5-alpine
    container_name: sck-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres_db
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - sck

  backend:
    image: cosmtrek/air
    container_name: sck-backend
    working_dir: /app
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_URL=postgres://postgres:123456@sck-database:5432/postgres_db
    volumes:
      - ./:/app/
    networks:
      - sck

networks:
  sck: {}
