basePath: /
definitions:
  models.BankName:
    enum:
    - KASIKORN BANK
    - BANGKOK BANK
    - KRUNG THAI BANK
    - BANK OF AYUDHYA
    - CIMB THAI BANK
    - TMBTHANACHART BANK
    - SIAM COMMERCIAL BANK
    - GOVERNMENT SAVINGS BANK
    - BANK NOT SELECTED
    type: string
    x-enum-varnames:
    - KBANK
    - BBL
    - KTB
    - BAY
    - CIMB
    - TTB
    - SCB
    - GSB
    - "NULL"
  models.ErrorResponse:
    properties:
      code:
        example: 500
        type: integer
      message:
        example: internal server error
        type: string
      name:
        example: internal-server-error
        type: string
    type: object
  models.Greeting:
    properties:
      message:
        example: Hello, World
        type: string
    type: object
  models.Property:
    properties:
      address:
        example: 123/4
        type: string
      alley:
        example: Pattaya Nua 78
        type: string
      country:
        example: Thailand
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      description:
        example: Et sequi dolor praes
        type: string
      district:
        example: Bang Phli
        type: string
      images:
        items:
          $ref: '#/definitions/models.PropertyImage'
        type: array
      owner_id:
        description: foreign key
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      postal_code:
        example: "69096"
        type: string
      project_name:
        example: Supalai
        type: string
      propertyId:
        type: string
      province:
        example: Pattaya
        type: string
      renting:
        $ref: '#/definitions/models.RentingProperty'
      residential_type:
        example: Condo
        type: string
      selling:
        $ref: '#/definitions/models.SellingProperty'
      street:
        example: Pattaya
        type: string
      sub_district:
        example: Bang Bon
        type: string
      updatedAt:
        type: string
    type: object
  models.PropertyImage:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      updatedAt:
        type: string
      url:
        example: https://image_url.com/abcd
        type: string
    type: object
  models.RegisteredType:
    enum:
    - EMAIL
    - GOOGLE
    type: string
    x-enum-varnames:
    - EMAIL
    - GOOGLE
  models.RentingProperty:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      is_occupied:
        example: true
        type: boolean
      price_per_month:
        example: 12345.67
        type: number
      updatedAt:
        type: string
    type: object
  models.SellingProperty:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      is_sold:
        example: true
        type: boolean
      price:
        example: 12345.67
        type: number
      updatedAt:
        type: string
    type: object
  models.Session:
    properties:
      email:
        example: admim@email.com
        type: string
      registered_type:
        allOf:
        - $ref: '#/definitions/models.RegisteredType'
        example: EMAIL / GOOGLE
      session_type:
        allOf:
        - $ref: '#/definitions/models.SessionType'
        example: LOGIN / REGISTER
    type: object
  models.SessionType:
    enum:
    - REGISTER
    - LOGIN
    type: string
    x-enum-varnames:
    - SessionRegister
    - SessionLogin
  models.Users:
    properties:
      bank_account_number:
        example: "1234567890"
        type: string
      bank_name:
        allOf:
        - $ref: '#/definitions/models.BankName'
        example: KBANK
      citizen_card_image_url:
        example: https://image_url.com/abcd
        type: string
      citizen_id:
        example: "1234567890123"
        type: string
      createdAt:
        type: string
      credit_card_cvv:
        example: "123"
        type: string
      credit_card_expiration_month:
        example: "12"
        type: string
      credit_card_expiration_year:
        example: "2023"
        type: string
      credit_card_number:
        example: "1234567890123456"
        type: string
      credit_cardholder_name:
        example: JOHN DOE
        type: string
      deletedAt:
        type: string
      email:
        example: email@email.com
        type: string
      first_name:
        example: John
        type: string
      is_verified:
        example: false
        type: boolean
      last_name:
        example: Doe
        type: string
      password:
        example: password1234
        type: string
      phone_number:
        example: "0812345678"
        type: string
      profile_image_url:
        example: https://image_url.com/abcd
        type: string
      registered_type:
        allOf:
        - $ref: '#/definitions/models.RegisteredType'
        example: EMAIL
      updatedAt:
        type: string
      userId:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: Bangkok Property Matchmaking Platform API docs
  title: Bangkok Property Matchmaking Platform
  version: "1.0"
paths:
  /api/v1/greeting:
    get:
      description: says hello, world
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Greeting'
      summary: Greeting
      tags:
      - greeting
  /api/v1/login:
    post:
      description: Login with email and password
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Property'
        "400":
          description: Empty or invalid credentials
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Password mismatch
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Login with email
      tags:
      - auth
  /api/v1/logout:
    post:
      description: Logout
      responses:
        "200":
          description: OK
      summary: Logout
      tags:
      - auth
  /api/v1/oauth/google:
    get:
      description: Redirect to this endpoint to login with Google OAuth2. When logging
        in is completed, the redirection to /register in client will occur.
      responses:
        "307":
          description: Temporary Redirect
      summary: Login with Google
      tags:
      - auth
  /api/v1/properties:
    get:
      description: Get all properties
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Property'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get all properties
      tags:
      - property
  /api/v1/property/:id:
    get:
      description: Get property by its id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Property'
        "400":
          description: Invalid property id
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Property id not found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get property by id
      tags:
      - property
  /api/v1/register:
    post:
      description: Create a user by prasing the body
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Users'
        "400":
          description: Invalid user info
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Register *use cookies*
      tags:
      - users
  /api/v1/user/:userId:
    delete:
      description: Delete a user by its id
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Invalid user id
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Delete user by id
      tags:
      - users
    get:
      description: Get a user by its id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Users'
        "400":
          description: Invalid user id
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get user by id
      tags:
      - users
    put:
      description: Update a user with the given id by parsing the body
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Users'
        "400":
          description: Invalid user info
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Update user by id
      tags:
      - users
  /api/v1/user/greeting:
    get:
      description: says hello to current user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Greeting'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Greeting with auth required *use cookies*
      tags:
      - greeting
  /api/v1/user/me:
    get:
      description: Get current user info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Users'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get current user info *use cookies*
      tags:
      - users
  /api/v1/user/me/registered:
    get:
      description: Get user registered type
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Session'
      summary: Get user registered type *use cookies*
      tags:
      - users
  /api/v1/users:
    get:
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Users'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get all users
      tags:
      - users
swagger: "2.0"
